### ISSUE TITLE
插件图标显示灰色，但其实能访问网页数据，点击也能进入阅读模式

### ISSUE THREAD

**Issue by bradchen09** [yuiitsu/Fika-Chrome#4]
**Describe the bug**
插件图标显示灰色，但其实能访问网页数据，点击也能进入阅读模式

**To Reproduce**
1. Go to 'https://www.figma.com/blog/design-on-a-deadline-how-notion-pulled-itself-back-from-the-brink-of-failure/?utm_source=wanqu.co&utm_campaign=Wanqu+Daily&utm_medium=website'
2. Fika 插件图标显示灰色
3. Click on 'Fika 插件图标'
4. 成功进入阅读模式

**Expected behavior**
插件图标显示彩色

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version  72.0.3626.121（正式版本） （64 位）

**Additional context**

**Comment by yuiitsu** [comment]
测试是正常的，可能是网络原因，多刷新几次

**Comment by bradchen09** [comment]
复测正常了
